### ISSUE TITLE
Pretrained model not available

### ISSUE THREAD

**Issue by sahertariq07** [ChrisMats/seemingly_uninformative_labels#2]
Hi Chris!
I'm trying to replicate your study for my data. But you didn't provide any pre-trained model here. Do I have to retrain to run it or is there any other source to download. Waiting for your response. 
Thank you.

**Comment by ChrisMats** [comment]
Hi @sahertariq07,

Unfortunately you have to retrain the models since we haven’t updated the pretrained weights somewhere.

**Comment by sahertariq07** [comment]
Okay...... Thank you Chris for your quick response.
